apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: domain-router
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "21"
    spec:
      containerConcurrency: 13
      containers:
        - image: gcr.io/${PROJECT_ID}/domain-router:latest
          ports:
            - containerPort: 4301
          env:
            - name: PORT
              value: "4301"
            - name: HEADY_ENV
              value: "prod"
          startupProbe:
            httpGet:
              path: /health/live
              port: 4301
          livenessProbe:
            httpGet:
              path: /health/live
              port: 4301
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4301
