/**
 * HEADY_BRAND:BEGIN
 * Heady Systems - Sacred Geometry :: Organic Systems :: Breathing Interfaces
 * Generated by create-heady-agent
 * HEADY_BRAND:END
 */

'use strict';
const logger = console;

const { Agent } = require('./agent');

// Phi-scaled defaults
const PHI = 1.618033988749895;
const HEARTBEAT_MS = 29034; // phi^7
const DEFAULT_TIMEOUT_MS = Math.round(5000 * PHI); // 8090ms
const DEFAULT_POOL_SIZE = 8; // Fibonacci

async function main() {
  const agent = new Agent({
    name: '{{PROJECT_NAME}}',
    timeout: DEFAULT_TIMEOUT_MS,
    poolSize: DEFAULT_POOL_SIZE,
    heartbeatInterval: HEARTBEAT_MS,
  });

  await agent.initialize();

  logger.info(`[{{PROJECT_NAME}}] Agent started with phi-scaled defaults`);
  logger.info(`  timeout: ${DEFAULT_TIMEOUT_MS}ms`);
  logger.info(`  poolSize: ${DEFAULT_POOL_SIZE}`);
  logger.info(`  heartbeat: ${HEARTBEAT_MS}ms`);

  // Main loop with phi-scaled heartbeat
  const interval = setInterval(async () => {
    const status = agent.getStatus();
    logger.info(`[{{PROJECT_NAME}}] heartbeat — status: ${status.state}`);
  }, HEARTBEAT_MS);

  process.on('SIGINT', () => {
    clearInterval(interval);
    agent.shutdown();
    process.exit(0);
  });

  // Execute agent's primary task
  const result = await agent.execute({ type: 'init' });
  logger.info(`[{{PROJECT_NAME}}] Initial execution result:`, result);
}

main().catch(console.error);
